### ISSUE TITLE
Issue with the "npm install"

### ISSUE THREAD

**Issue by stinkycol** [Tom-Hirschberger/MMM-ProfileControl#2]
I am having an issue with the "npm install" for the module. These are the steps I took for installation:

pi@raspberrypi: ~/MagicMirror/modules $ git clone https://github.com/Tom-Hirschberger/MMM-ProfileControl.git
Cloning into 'MMM-ProfileControl'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 79 (delta 47), reused 52 (delta 25), pack-reused 0
Receiving objects: 100% (79/79), 490.74 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (47/47), done.
pi@raspberrypi: ~/MagicMirror/modules $ cd MMM-ProfileControl
pi@raspberrypi: ~/MagicMirror/modules/MMM-ProfileControl $ npm install
npm error Invalid or unexpected token

npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-05-02T18_32_51_812Z-debug-0.log
pi@raspberrypi:~/MagicMirror/modules/MMM-ProfileControl $ nano /home/pi/.npm/_logs/2024-05-02T18_32_51_812Z-debug-0.log

The error log is:

0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.6.0
2 info using node@v20.12.2
3 silly config:load:file:/usr/lib/node_modules/npm/npmrc
4 silly config:load:file:/home/pi/MagicMirror/modules/MMM-ProfileControl/.npmrc
5 silly config:load:file:/home/pi/.npmrc
6 silly config:load:file:/usr/etc/npmrc
7 verbose title npm install
8 verbose argv "install"
9 verbose logfile logs-max:10 dir:/home/pi/.npm/_logs/2024-05-02T18_32_51_812Z-
10 verbose logfile /home/pi/.npm/_logs/2024-05-02T18_32_51_812Z-debug-0.log
11 verbose stack /usr/lib/node_modules/npm/node_modules/just-diff-apply/index.cjs:1
11 verbose stack ���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������>
11 verbose stack
11 verbose stack
11 verbose stack SyntaxError: Invalid or unexpected token
11 verbose stack     at internalCompileFunction (node:internal/vm:128:18)
11 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1280:20)
11 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1332:27)
11 verbose stack     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
11 verbose stack     at Module.load (node:internal/modules/cjs/loader:1206:32)
11 verbose stack     at Module._load (node:internal/modules/cjs/loader:1022:12)
11 verbose stack     at Module.require (node:internal/modules/cjs/loader:1231:19)
11 verbose stack     at require (node:internal/modules/helpers:179:18)
11 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/parse-conflict-json/lib/index.js:3:23)
11 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1369:14)
12 verbose cwd /home/pi/MagicMirror/modules/MMM-ProfileControl
13 verbose Linux 6.6.20+rpt-rpi-v8
14 verbose node v20.12.2
15 verbose npm  v10.6.0
16 error Invalid or unexpected token
17 verbose exit 1
18 verbose code 1
19 error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-05-02T18_32_51_812Z-debug-0.log

**Comment by Tom-Hirschberger** [comment]
Hi and interesting.
Tried the installation on both my Raspberries a few seconds ago and it works without any problems.
Big difference is I am using older Node and Npm versions.
The module should work without the installation step as no external dependencies are referenced at the moment.
If not there might be broken something with your node or npm installation.
Do you have problems with any other module installation, too?

**Comment by stinkycol** [comment]
Hi, no this is the first time something has failed at the installation. I will try the module without the install and let you know.

**Comment by stinkycol** [comment]
Hi, it works fine thank you for the advice.
